---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: blue-build-custom-system
# description will be included in the image's metadata
description: This is my personal OS image with my favorite tools.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-dx
image-version: stable # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  # https://blue-build.org/blog/dnf-module/
  - type: dnf
    # https://github.com/boredsquirrel/browserscript-fedora-atomic
    repos:
      files:
        - vivaldi-x86_64.repo
        - https://openrazer.github.io/hardware:razer.repo
      copr:
        - secureblue/bubblejail
      keys:
        - https://repo.vivaldi.com/archive/linux_signing_key.pub
        - https://download.opensuse.org/repositories/hardware:/razer/Fedora_%OS_VERSION%/repodata/repomd.xml.key
    install:
      packages:
        - vivaldi-stable
        - bubblejail
        - openrazer-daemon
    optfix:
      - vivaldi

  - type: default-flatpaks
    configurations:
      - notify: false # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - app.polychromatic.controller
          - com.bitwarden.desktop
          - com.discordapp.Discord
          - com.github.k4zmu2a.spacecadetpinball
          - com.github.mtkennerly.ludusavi
          - com.hunterwittenborn.Celeste
          - com.obsproject.Studio
          - com.usebottles.bottles
          - io.mpv.Mpv
          - me.proton.Mail
          - org.fcitx.Fcitx5
          - org.fcitx.Fcitx5.Addon.McBopomofo
          - org.keepassxc.KeePassXC
          - org.libreoffice.LibreOffice
          - org.mozilla.Thunderbird
          - org.prismlauncher.PrismLauncher
          - org.sonic3air.Sonic3AIR
          # Branches not support in v2 because it use `flathub.org/api/v2/stats/` API.
          # - org.freedesktop.Platform.VulkanLayer.gamescope//24.08
          # - org.freedesktop.Platform.VulkanLayer.vkBasalt//24.08
          # - org.freedesktop.Platform.VulkanLayer.MangoHud//24.08
          # - org.freedesktop.Platform.VulkanLayer.OBSVkCapture//24.08
      - scope: user # Also add Flathub user repo, but no user packages

  - type: bling
    install:
      - 1password

  - type: script
    snippets:
      - "install -d -m 0755 /nix /snap"

  - type: kargs
    arch: x86_64  # only inject kernel arguments to these specific OS architectures
    kargs:  # Add kargs about virtualization.
      - kvm.ignore_msrs=1
      - kvm.report_ignored_msrs=0

  - type: systemd
    system:
      enabled:
        - sshd.service

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
